#
# Module manifest for module 'sqlserver-toolkit'
#
# Generated by: Kasper Brandenburg
#
# Generated on: June 21, 2016
#

@{

# Script module or binary module file associated with this manifest.
ModuleToProcess = 'sqlserver-toolkit.psm1'

# Version number of this module.
ModuleVersion = '0.1.2'

# ID used to uniquely identify this module
GUID = '8F149ACD-6B12-4786-99AE-595BB93A1F7B'

CompanyName = 'Home'
CopyRight = 'Copyright 2016 Kasper Brandenburg'

# Author of this module
Author = 'Kasper Brandenburg'

# Description of the functionality provided by this module
Description = 'SQL Server toolkit module, more information on https://github.com/kasperbrandenburg/sqlserver-toolkit'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module.
# ModuleList = @()

# List of all files packaged with this module
FileList = @('PowerShellLogging.psm1','PowerShellLogging.psd1', 'Functions\SQL-Agent\Invoke-BackupSqlAgentJobs.ps1', 'Functions\SQL-Agent\Invoke-RestoreSqlAgentJobs.ps1')

}